#!/usr/bin/perl

my $base = "testcases";
if (scalar(@ARGV) > 2) { $base = $ARGV[1]; }
my @files = `find $base | grep \.class`;

foreach my $file (@files) {
  if (0 != system("java -classpath ../out/production/cfr org.benf.cfr.reader.Main $file")) {
    print "\n\nDied while processing:\n";
    print "$file\n";
    die;
  }
  die if (++$x > 20);
}